# Generated by Django 3.1.1 on 2020-10-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamiento', '0001_initial'),
        ('gestionProcedimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('codigoMaterial', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequerido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('codigoMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionMateriales.material')),
                ('idProcedimientoModalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProcedimientos.procedimientomodalidad')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PSOL', 'Por Solicitar'), ('SOLI', 'Solicitado'), ('RECI', 'Recibido')], default=('PSOL', 'Por Solicitar'), max_length=15)),
                ('casaMedica', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaSolicitud', models.DateField()),
                ('fechaEstimada', models.DateField()),
                ('fechaRecibido', models.DateField()),
                ('codigoMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionMateriales.material')),
                ('idAgendaProcedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.agendaprocedimiento')),
            ],
        ),
    ]
