# Generated by Django 3.1.1 on 2020-10-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMateriales', '0002_auto_20201001_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamaterial',
            name='casaMedica',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
