# Generated by Django 3.1.1 on 2020-10-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('idModalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('codigoProcedimiento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CMA', 'Cirugia mayor'), ('CME', 'Cirugia menor'), ('CAM', 'Cirugia ambulatora')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimientoModalidad',
            fields=[
                ('idProcedimientoModalidad', models.AutoField(primary_key=True, serialize=False)),
                ('camaUCI', models.BooleanField()),
                ('bancoSangre', models.BooleanField()),
                ('codigoProcedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProcedimientos.procedimiento')),
                ('idModalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProcedimientos.modalidad')),
            ],
        ),
    ]
