# Generated by Django 3.1.1 on 2020-10-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProcedimientos', '0002_auto_20201001_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidad',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='tipo',
            field=models.CharField(choices=[('CMA', 'Cirugia mayor'), ('CME', 'Cirugia menor'), ('CAM', 'Cirugia ambulatoria')], max_length=30),
        ),
        migrations.AlterField(
            model_name='procedimientomodalidad',
            name='codigoProcedimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='gestionProcedimientos.procedimiento'),
        ),
        migrations.AlterField(
            model_name='procedimientomodalidad',
            name='idModalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='gestionProcedimientos.modalidad'),
        ),
    ]
