# Generated by Django 3.1.1 on 2020-10-07 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProcedimientos', '0003_auto_20201005_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimientomodalidad',
            name='codigoProcedimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidadesProc', to='gestionProcedimientos.procedimiento'),
        ),
    ]
