# Generated by Django 3.1.1 on 2020-10-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEquipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendaequipo',
            table='AgendaEquipo',
        ),
        migrations.AlterModelTable(
            name='equipo',
            table='Equipo',
        ),
        migrations.AlterModelTable(
            name='equiporequerido',
            table='EquipoRequerido',
        ),
    ]
