# Generated by Django 3.1.1 on 2020-10-08 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEspecialistas', '0003_auto_20201005_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaespecialista',
            name='idEspecialidad',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='gestionEspecialistas.especialidad'),
        ),
    ]
