# Generated by Django 3.1.1 on 2020-10-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEspecialistas', '0004_agendaespecialista_idespecialidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendaespecialista',
            old_name='idEspecialidad',
            new_name='codigoEspecialidad',
        ),
    ]
