# Generated by Django 3.1.1 on 2020-10-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEspecialistas', '0006_auto_20201008_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='registroMedico',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
