# Generated by Django 3.1.1 on 2020-10-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=15, unique=True)),
                ('tipoIdentificacion', models.CharField(choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta de identidad'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('MS', 'Menor sin identificación'), ('AS', 'Adulto sin identidad')], max_length=3)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=15)),
            ],
        ),
    ]
