# Generated by Django 3.1.1 on 2020-10-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEspecialistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendaespecialista',
            table='AgendaEspecialista',
        ),
        migrations.AlterModelTable(
            name='especialidad',
            table='Especialidad',
        ),
        migrations.AlterModelTable(
            name='especialidadrequerida',
            table='EspecialidadRequerida',
        ),
        migrations.AlterModelTable(
            name='especialista',
            table='Especialista',
        ),
    ]
