# Generated by Django 3.1.1 on 2020-10-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEspecialistas', '0005_auto_20201008_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaespecialista',
            name='idEspecialista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionEspecialistas.especialista'),
        ),
    ]
