# Generated by Django 3.1.1 on 2020-10-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDocumentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentacionrequerida',
            table='DocumentacionRequerida',
        ),
        migrations.AlterModelTable(
            name='documento',
            table='Documento',
        ),
        migrations.AlterModelTable(
            name='documentoadjunto',
            table='DocumentoAdjunto',
        ),
    ]
