# Generated by Django 3.1.1 on 2020-10-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProcedimientos', '0003_auto_20201005_1634'),
        ('gestionDocumentos', '0002_auto_20201001_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionrequerida',
            name='idProcedimientoModalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestionProcedimientos.procedimientomodalidad'),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
