# Generated by Django 3.1.1 on 2020-10-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionSalas', '0001_initial'),
        ('gestionUsuarios', '0001_initial'),
        ('gestionPacientes', '0001_initial'),
        ('gestionProcedimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaProcedimiento',
            fields=[
                ('idAgendaProcedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField(blank=True, null=True)),
                ('estadoFecha', models.CharField(choices=[('PEND', 'Pendiente'), ('CONF', 'Confirmado'), ('CANC', 'Cancelado')], default=('PEND', 'Pendiente'), max_length=15)),
                ('cama', models.BooleanField()),
                ('estadoCama', models.CharField(choices=[('AGEN', 'Agendado'), ('PEND', 'Pendiente')], default=('PEND', 'Pendiente'), max_length=15)),
                ('bancoSangre', models.BooleanField()),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('idAcudiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acudiente', to='gestionPacientes.persona')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='gestionPacientes.persona')),
                ('idProcedimientoModalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProcedimientos.procedimientomodalidad')),
                ('idSala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionSalas.sala')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.usuario')),
            ],
        ),
    ]
