# Generated by Django 3.1.1 on 2020-10-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0003_auto_20201005_1634'),
        ('agendamiento', '0004_agendaprocedimiento_estadosala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaprocedimiento',
            name='idAcudiente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Acudiente', to='gestionPacientes.persona'),
            preserve_default=False,
        ),
    ]
