# Generated by Django 3.1.1 on 2020-11-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0005_auto_20201027_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaprocedimiento',
            name='estadoCama',
            field=models.CharField(blank=True, choices=[('AGEN', 'Agendado'), ('PEND', 'Pendiente')], default=('PEND', 'Pendiente'), max_length=15, null=True),
        ),
    ]
