# Generated by Django 3.1.1 on 2020-10-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamiento', '0001_initial'),
        ('gestionProcedimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('caduca', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('RECI', 'Recibido'), ('APRO', 'Aprobado'), ('RECH', 'Rechazado')], default=('PEND', 'Pendiente'), max_length=15)),
                ('fechaVecimiento', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('path', models.FileField(max_length=500, upload_to=None)),
                ('fechaDocRecibido', models.DateField(blank=True, null=True)),
                ('codigoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionDocumentos.documento')),
                ('idAgendaProcedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.agendaprocedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionRequerida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionDocumentos.documento')),
                ('idProcedimientoModalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProcedimientos.procedimientomodalidad')),
            ],
        ),
    ]
