# Generated by Django 3.1.1 on 2020-10-07 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProcedimientos', '0004_auto_20201006_2207'),
        ('gestionDocumentos', '0003_auto_20201005_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='codigo',
            new_name='codigoDocumento',
        ),
        migrations.AlterField(
            model_name='documentacionrequerida',
            name='codigoDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentosToProc', to='gestionDocumentos.documento'),
        ),
        migrations.AlterField(
            model_name='documentacionrequerida',
            name='idProcedimientoModalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentosRequeridos', to='gestionProcedimientos.procedimientomodalidad'),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
