# Generated by Django 3.1.1 on 2020-10-08 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProcedimientos', '0004_auto_20201006_2207'),
        ('gestionDocumentos', '0004_auto_20201006_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionrequerida',
            name='codigoDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionDocumentos.documento'),
        ),
        migrations.AlterField(
            model_name='documentacionrequerida',
            name='idProcedimientoModalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestionProcedimientos.procedimientomodalidad'),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=None),
        ),
    ]
