# Generated by Django 3.1.1 on 2020-10-10 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDocumentos', '0005_auto_20201007_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoadjunto',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='Documents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
