# Generated by Django 3.1.1 on 2020-10-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamiento', '0001_initial'),
        ('gestionProcedimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('codigoEquipo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoRequerido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('codigoEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEquipos.equipo')),
                ('idProcedimientoModalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProcedimientos.procedimientomodalidad')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AGEN', 'Agendado'), ('PEND', 'Pendiente')], default=('PEND', 'Pendiente'), max_length=15)),
                ('codigoEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEquipos.equipo')),
                ('idAgendaProcedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.agendaprocedimiento')),
            ],
        ),
    ]
