# Generated by Django 3.1.1 on 2020-10-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendaprocedimiento',
            table='AgendaProcedimiento',
        ),
    ]
