# Generated by Django 3.1.1 on 2020-10-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0003_auto_20201001_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaprocedimiento',
            name='estadoSala',
            field=models.CharField(choices=[('AGEN', 'Agendado'), ('PEND', 'Pendiente')], default=('PEND', 'Pendiente'), max_length=30),
        ),
    ]
