# Generated by Django 3.1.1 on 2020-11-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0002_auto_20201001_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
