# Generated by Django 3.1.1 on 2020-10-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMateriales', '0003_auto_20201005_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamaterial',
            name='fechaEstimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamaterial',
            name='fechaRecibido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamaterial',
            name='fechaSolicitud',
            field=models.DateField(blank=True, null=True),
        ),
    ]
