# Generated by Django 3.1.1 on 2020-10-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0003_auto_20201001_1841'),
        ('gestionMateriales', '0004_auto_20201008_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamaterial',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='agendamaterial',
            unique_together={('codigoMaterial', 'idAgendaProcedimiento')},
        ),
    ]
